services:
  # Backend API service
  - type: web
    name: iot-backend
    runtime: node
    rootDir: apps/server
    buildCommand: cd ../.. && pnpm install && pnpm turbo run build --filter=server
    startCommand: node dist/index.js
    plan: free # Explicitly set free tier
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # This will be set manually in Render dashboard
      - key: API_URL
        fromService:
          type: web
          name: iot-backend
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /health

  # Frontend static site
  - type: web
    name: iot-frontend
    runtime: static
    rootDir: apps/iot-app
    buildCommand: cd ../.. && pnpm install && pnpm turbo run build --filter=iot-app
    startCommand: serve -s dist
    plan: free # Explicitly set free tier
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          type: web
          name: iot-backend
          envVarKey: RENDER_EXTERNAL_URL
