services:  - type: web
    name: iot-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: API_URL
        fromService:
          type: web
          name: iot-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: CLIENT_URL
        fromService:
          type: web
          name: iot-frontend
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /health

  - type: web
    name: iot-frontend
    runtime: node
    rootDir: apps/iot-app
    buildCommand: cd ../.. && pnpm install && ./node_modules/.bin/turbo run build --filter=iot-app
    startCommand: npx serve dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          type: web
          name: iot-backend
          envVarKey: RENDER_EXTERNAL_URL
