services:
  - type: web
    name: iot-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: API_URL
        fromService:
          type: web
          name: iot-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: CLIENT_URL
        fromService:
          type: web
          name: iot-frontend
          envVarKey: RENDER_EXTERNAL_URL
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
    healthCheckPath: /health

  - type: web
    name: iot-frontend
    runtime: node
    rootDir: .
    buildCommand: |
      npm install -g pnpm@9.0.0
      pnpm install
      pnpm run build --filter=iot-app
    startCommand: cd apps/iot-app && npx serve dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          type: web
          name: iot-backend
          envVarKey: RENDER_EXTERNAL_URL
