// import axios from "axios";
import apiClient from "../api/axiosConfig";

// Import the configured apiClient

// Define the Patient interface based on the backend model
// Ensure this matches IPatient in apps/server/src/models/patient.model.ts
export interface Patient {
  _id: string; // MongoDB default ID
  id_patient: string;
  id_device: string;
  name: string;
  room: number;
  illness?: string;
  age?: number;
  notes?: string;
}

// --- Patient API Functions (using imported apiClient) ---

export const fetchAllPatients = async (): Promise<Patient[]> => {
  try {
    // Note: URL should now be relative to any baseURL set in axiosConfig, or full path if none set
    const response = await apiClient.get("/api/patients"); // Use relative path
    // Adjust based on actual backend response structure if necessary
    return response.data.data || response.data; // Handle potential pagination wrapper
  } catch (error) {
    // Basic error handling, consider more robust logging or user feedback
    console.error("Error fetching patients:", error);
    throw error; // Re-throw to allow components to handle it
  }
};

export const fetchPatientById = async (id: string): Promise<Patient> => {
  try {
    const response = await apiClient.get(`/api/patients/${id}`);
    return response.data;
  } catch (error) {
    console.error(`Error fetching patient ${id}:`, error);
    throw error;
  }
};

// Use Partial<Omit<Patient, '_id'>> for update data flexibility
export const updatePatient = async (
  id: string,
  data: Partial<Omit<Patient, "_id">>,
): Promise<Patient> => {
  try {
    const response = await apiClient.patch(`/api/patients/${id}`, data);
    return response.data;
  } catch (error) {
    console.error(`Error updating patient ${id}:`, error);
    throw error;
  }
};

// Use Omit<Patient, '_id'> for create data, as _id is generated by DB
export const createPatient = async (data: Omit<Patient, "_id">): Promise<Patient> => {
  try {
    const response = await apiClient.post("/api/patients", data);
    return response.data;
  } catch (error) {
    console.error("Error creating patient:", error);
    throw error;
  }
};

export const deletePatient = async (id: string): Promise<{ message: string }> => {
  try {
    // Assuming the backend returns { message: "Patient deleted" }
    const response = await apiClient.delete(`/api/patients/${id}`);
    return response.data;
  } catch (error) {
    console.error(`Error deleting patient ${id}:`, error);
    throw error;
  }
};
